baseURL: "https://github.com/SweiiHuang/sweiihuang.github.io" # ç¶²ç«™çš„åŸºç¤URL
title: Fill the Gap # ç¶²ç«™æ¨™é¡Œ
paginate: 5 # æ¯é é¡¯ç¤ºçš„æ–‡ç« æ•¸é‡
theme: PaperMod # ä½¿ç”¨çš„ä¸»é¡Œåç¨±

enableRobotsTXT: true # å•Ÿç”¨Robots.txtæ–‡ä»¶ï¼Œå…è¨±æœå°‹å¼•æ“çˆ¬å–ç¶²ç«™
buildDrafts: false # ä¸æ§‹å»ºè‰ç¨¿ç‹€æ…‹çš„å…§å®¹
buildFuture: false # ä¸æ§‹å»ºè¨­ç½®åœ¨æœªä¾†ç™¼å¸ƒçš„å…§å®¹
buildExpired: false # ä¸æ§‹å»ºå·²éæœŸçš„å…§å®¹

googleAnalytics: # Google Analyticsçš„è¿½è¹¤ä»£ç¢¼

minify:
  disableXML: true # ç¦ç”¨XMLå£“ç¸®
  minifyOutput: true # å•Ÿç”¨è¼¸å‡ºå£“ç¸®

params:
  env: production # è¨­å®šç’°å¢ƒç‚ºç”Ÿç”¢ç’°å¢ƒï¼Œå•Ÿç”¨Google Analyticsã€OpenGraphã€Twitterå¡ç‰‡å’Œçµæ§‹åŒ–æ•¸æ“š
  title: Fill the Gap # ç¶²ç«™æ¨™é¡Œ
  description: "Not All Who Wander Are Lost" # ç¶²ç«™æè¿°
  keywords: [Blog, Portfolio, PaperMod] # é—œéµå­—åˆ—è¡¨
  author: SW # ä½œè€…åç¨±
  # author: ["Me", "You"]             # å¤šä½ä½œè€…
  images: ["<link or path of image for opengraph, twitter-cards>"] # OpenGraphå’ŒTwitterå¡ç‰‡çš„åœ–ç‰‡é€£çµæˆ–è·¯å¾‘
  DateFormat: "January 2, 2006" # æ—¥æœŸæ ¼å¼
  defaultTheme: auto # é è¨­ä¸»é¡Œï¼Œautoæœƒè‡ªå‹•æ ¹æ“šç”¨æˆ¶çš„ç³»çµ±è¨­ç½®åˆ‡æ›ï¼ˆå¯é¸å€¼ï¼šdark, lightï¼‰
  disableThemeToggle: false # æ˜¯å¦ç¦ç”¨ä¸»é¡Œåˆ‡æ›é–‹é—œ

  ShowReadingTime: true # é¡¯ç¤ºé–±è®€æ™‚é–“
  ShowShareButtons: true # é¡¯ç¤ºåˆ†äº«æŒ‰éˆ•
  ShowPostNavLinks: true # é¡¯ç¤ºæ–‡ç« å°èˆªé€£çµ
  ShowBreadCrumbs: true # é¡¯ç¤ºéºµåŒ…å±‘å°èˆª
  ShowCodeCopyButtons: true # ä¸é¡¯ç¤ºä»£ç¢¼è¤‡è£½æŒ‰éˆ•
  ShowWordCount: true # é¡¯ç¤ºå­—æ•¸çµ±è¨ˆ
  ShowRssButtonInSectionTermList: true # åœ¨éƒ¨åˆ†åˆ—è¡¨ä¸­é¡¯ç¤ºRSSæŒ‰éˆ•
  UseHugoToc: true # ä½¿ç”¨Hugoå…§ç½®çš„ç›®éŒ„ï¼ˆTable of Contentsï¼‰
  disableSpecial1stPost: false # ä¸ç¦ç”¨ç‰¹åˆ¥æ¨£å¼çš„ç¬¬ä¸€ç¯‡æ–‡ç« 
  disableScrollToTop: false # ä¸ç¦ç”¨å›åˆ°é ‚éƒ¨æŒ‰éˆ•
  comments: true # ä¸å•Ÿç”¨è©•è«–åŠŸèƒ½
  hidemeta: false # ä¸éš±è—å…ƒæ•¸æ“š
  hideSummary: false # ä¸éš±è—æ‘˜è¦
  showtoc: true # ä¸é¡¯ç¤ºç›®éŒ„
  tocopen: false # é è¨­ä¸å±•é–‹ç›®éŒ„

  assets:
    # disableHLJS: true               # ç¦ç”¨highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>" # Faviconçš„é€£çµæˆ–çµ•å°URL
    favicon16x16: "<link / abs url>" # 16x16 Faviconçš„é€£çµæˆ–çµ•å°URL
    favicon32x32: "<link / abs url>" # 32x32 Faviconçš„é€£çµæˆ–çµ•å°URL
    apple_touch_icon: "<link / abs url>" # Apple touchåœ–æ¨™çš„é€£çµæˆ–çµ•å°URL
    safari_pinned_tab: "<link / abs url>" # Safari Pinned Tabåœ–æ¨™çš„é€£çµæˆ–çµ•å°URL

  label:
    text: "A Lifeâ€™s Eclipse" # æ¨™ç±¤æ–‡æœ¬
    icon: /apple-touch-icon.png # æ¨™ç±¤åœ–æ¨™
    iconHeight: 35 # æ¨™ç±¤åœ–æ¨™é«˜åº¦

  profileMode:
    enabled: false # é ˆé¡¯å¼è¨­ç½®ç‚ºtrueä»¥å•Ÿç”¨
    title: ExampleSite # æ¨™é¡Œ
    subtitle: "This is subtitle" # å‰¯æ¨™é¡Œ
    imageUrl: "<img location>" # åœ–ç‰‡URL
    imageWidth: 120 # åœ–ç‰‡å¯¬åº¦
    imageHeight: 120 # åœ–ç‰‡é«˜åº¦
    imageTitle: my image # åœ–ç‰‡æ¨™é¡Œ
    buttons: # æŒ‰éˆ•é…ç½®
      - name: Posts
        url: posts
      - name: Tags
        url: tags
    socialIcons: # optional
      - name: "<platform>"
        url: "<link>"
      - name: "<platform 2>"
        url: "<link2>"

  homeInfoParams:
    Title: "Hi there ğŸ™‹ğŸ»â€â™€ï¸" # ä¸»è¦æ¨™é¡Œ
    Content: Inspired by the freedom of wandering, sometimes stepping away from the familiar becomes the only way to find oneself.

  #From Cubicle to Code

  socialIcons:
    - name: medium # ç¤¾äº¤å¹³å°åç¨±
      url: "https://medium.com/@lagom247" # ç¤¾äº¤å¹³å°é€£çµ
    - name: github
      url: "https://github.com/SweiiHuang"

  # analytics:
  #   google:
  #     SiteVerificationTag:  # Googleç«™é»é©—è­‰æ¨™ç±¤
  #   bing:
  #     SiteVerificationTag:  # Bingç«™é»é©—è­‰æ¨™ç±¤
  #   yandex:
  #     SiteVerificationTag: # Yandexç«™é»é©—è­‰æ¨™ç±¤

  cover:
    hidden: true # åœ¨æ‰€æœ‰åœ°æ–¹éš±è—å°é¢ï¼Œä½†åœ¨çµæ§‹åŒ–æ•¸æ“šä¸­ä¸éš±è—
    hiddenInList: true # åœ¨åˆ—è¡¨é å’Œé¦–é éš±è—å°é¢
    hiddenInSingle: true # åœ¨å–®ç¯‡æ–‡ç« é éš±è—å°é¢

    image: "<image path/url>"
    # can also paste direct link from external site
    # ex. https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png
    alt: "<alt text>"
    caption: "<text>"
    relative: false # To use relative path for cover image, used in hugo Page-bundles

  # editPost:
  #   URL: "https://github.com/sweiihuang.github.io/content" # ç·¨è¼¯æ–‡ç« çš„URL
  #   Text: "Suggest Changes" # ç·¨è¼¯æŒ‰éˆ•æ–‡æœ¬
  #   appendFilePath: true # å°‡æ–‡ä»¶è·¯å¾‘é™„åŠ åˆ°ç·¨è¼¯é€£çµä¸­

  fuseOpts: # æœç´¢é…ç½®ï¼Œåƒè¦‹ï¼šhttps://fusejs.io/api/options.html
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # åƒè€ƒï¼šhttps://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main: # ä¸»èœå–®é…ç½®
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

pygmentsUseClasses: true # ä½¿ç”¨Pygmentsçš„CSSé¡
markup:
  highlight:
    noClasses: false # ä¸ç¦ç”¨CSSé¡
    # anchorLineNos: true            # è¡Œè™ŸåŠ éŒ¨é»
    # codeFences: true               # æ”¯æŒMarkdownä»£ç¢¼æ¡†
    # guessSyntax: true              # çŒœæ¸¬èªæ³•é«˜äº®
    # lineNos: true                  # é¡¯ç¤ºè¡Œè™Ÿ
    # style: monokai                 # é«˜äº®æ¨£å¼
